apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaos-app-r
rules:
  - apiGroups: [""]
    resources: ["pods", "deployments", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-app-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaos-app
subjects:
  - kind: ServiceAccount
    name: default
