apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
  namespace: chaos-framework
spec:
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
        - name: events
          image: redis:7.0-rc-alpine
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: events
  namespace: chaos-framework
spec:
  selector:
    app: events
  ports:
    - port: 6379
      targetPort: 6379
